#!/usr/bin/expect
# USE EXAMPLE. Creating an alias for git:
# git() { if [[ $1 == "push" || $1 == "pull" ]]; then $HOME/bin/ansbot '*?assword*' 'PASSWORD_HERE' ''/usr/bin/git "$@"''; else /usr/bin/git "$@"; fi;
# to unalias function use: unset -f git

set timeout 20

proc lshift {varname} {      
    upvar 1 $varname var
    set var [lassign $var first]
    return $first
}

set pattern [lshift argv]
set pass [lshift argv]

eval spawn {*}$argv

expect {
  timeout { return 0 }
  eof { return 0 }
  "$pattern"
}

send $pass\r;

interact
