#!/bin/bash
usage() { echo "$(basename $0) <file>.mkv
    HOW TO GET FLAC FILES FROM BLURAY AUDIO DISCS
    - First, use makemkv to get .mkv file from bluray audio disc (for 5.1 you should change the header codec from A_MS/ACM to A_PCM/INT/LIT with mkvmerge/mkvtoolnix-gui)
    - Then, use this script to get .flac files from .mkv as described above
    - Finally, use MusicBrainz Picard for writing tags and rename files accordingly" 1>&2; exit 1; }


### OPTIONS (hardcoded) ###
# audio track position on bluray disc
audiotrack=0
# songs to extract
firsttrack=0
lasttrack=99

i=0
for var in *
do
    mkvmerge -o out-$i.mkv "$var"
    # if [[ ! -f out-$i.mkv ]]; then
        # break
    # fi
    # convert mkv to wav
    mkvextract tracks out-$i.mkv $audiotrack:out-$i.wav
    ffmpeg -i out-$i.wav out-$i.flac
    ((i=i+1))
done

# clean mkv and temporary files
# rm $filename out*.wav out*.mkv

