#!/bin/bash
usage() { echo "$(basename $0) [-f <a4|a5|b4|b5|c4|c5>] [-m <breaks|rightbreaks|cont>] [-j <book|dual>] [-i <header|footer|body>] <filename>.md
- opciones:
    FORMATO
        -f a5 (modo por defecto): Formato de página A5 (el modo por defecto, -m, es 'rightbreaks')
        -f a4: Formato de página A4 (el modo por defecto, -m, es 'cont')
        -s escala: Factor de ampliación.
    MODO
        -m cont[inuous]: todo el texto contínuo, sin saltos de página
        -m breaks: partes y capítulos con saltos de página
        -m rightbreaks: partes y capítulos con saltos de página y comenzando siempre en la parte derecha (modo por defecto)
    JUNTAR
        -j dual: junta 2 páginas en cada A4 con ordenación estándar
        -j book: pone 2 páginas en cada A4 en formato folleto
    INCLUIR
        -i especifica que partes se incluyen en el documento (se pueden escoger varias especificando varias veces el parámetro)
    METADATOS
        -t título a incluir en los metadatos y nombre del pdf
        -a autor a incluir en los metadatos del pdf

- plantillas .tex (a incluir en el mismo directorio que el fichero .md):
        - header.tex: páginas iniciales del documento en formato latex
        - footer.tex: páginas finales del documento en formato latex" 1>&2; exit 1; }

dependencies() {
    if ! $(gem list | grep kramdown >/dev/null) ||
        ! dpkg -s texlive texlive-latex-recommended texlive-latex-extra texlive-lang-spanish psutils okular evince ruby-full &> /dev/null
    then
        echo -e "Some required dependencies were not found. Would you like to install them? (y/n) \c"
        read
        if [[ "$REPLY" = "y" ]]; then
            sudo apt-get install -y texlive texlive-latex-recommended texlive-latex-extra texlive-lang-spanish
            sudo apt-get install -y pdfjam
            sudo apt-get install -y evince
            sudo apt-get install -y ruby-full
            sudo gem install kramdown
        fi
    fi
}

##### PARSEO DE PARÁMETROS RECIBIDOS #####
# definición de parámetros por defecto
mode=scrbook
f=a5
j=default
m=default
s=default
included_args=()
included=()
included+=('header')
included+=('footer')
included+=('body')

# parámetros recibidos
while getopts ":f:i:j:m:s:t:a:" o; do
case "${o}" in
    f)
        f=${OPTARG}
        if [[ "$f" != 'a4' && "$f" != 'a5' && "$f" != 'b4' && "$f" != 'b5'  && "$f" != 'c4' && "$f" != 'c5' ]]; then usage; fi
        ;;
    m)
        m=${OPTARG}
        if [[ "$m" != 'cont' && "$m" != 'breaks' && "$m" != 'rightbreaks' ]]; then usage; fi
        ;;
    j)
        j=${OPTARG}
        if [[ "$j" != 'book' && "$j" != 'dual' ]]; then usage; fi
        ;;
    i)
        i=${OPTARG}
        if [[ "$i" != 'header' && "$i" != 'footer' && "$i" != 'body' ]]; then usage; fi
        included_args+=($i)
        ;;
    s)
        s=${OPTARG}
        if [[ ! "$s" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then usage; fi
        ;;
    t)
        t=${OPTARG}
        if [[ -z "$t" ]]; then usage; fi
        ;;
    a)
        a=${OPTARG}
        if [[ -z "$a" ]]; then usage; fi
        ;;
    *)
        usage
        ;;
esac
done

# si se han especificado por parametro partes a incluir sobreescrimos las que vienen por defecto
if [ ! -z $included_args ]; then
    included=(${included_args[*]})
fi

# comprobamos que el fichero pasado por parámetro exista
shift $(( OPTIND - 1 ))
if [[ ! -f $@ || -z $@ || ! $(echo $@ | grep '.md') ]]; then
    usage
fi


##### PREPARACIÓN ENTORNO #####
# comprobación de dependencias
dependencies
filename=`basename -s .md $@`
dirname=`dirname $@`
# cambio al directorio de trabajo
cd "$dirname"
# limpieza de ficheros generados en ejecuciones anteriores
rm "$filename".pdf "$filename".ps 2> /dev/null


##### CONVERSIÓN DE KRAMDOWN A LATEX #####
kramdown -o latex --template document "$filename".md > "$filename".tex


##### POSTPROCESO DEL FICHERO TEX #####
# se cambia regla horizontal por asteriscos
sed -i 's/\\rule{3in}{0.4pt}/* * */g' "$filename".tex
# puntos suspensivos sin espacios
sed -i 's/\\ldots{}/.../g' "$filename".tex
# guiones largos más largos
sed -i 's/--/---/g' "$filename".tex
# espacio vertical
sed -i 's/\/\/\//\\bigskip\\bigskip\\bigskip/g' "$filename".tex




##### INCLUIMOS PARTES SELECCIONADAS SEGÚN PARÁMETROS #####
sed -n '/\\begin{document}/,/\\end{document}/P' "$filename".tex | head -n-1 | tail -n+2 > body.tex

# añadimos cabecera (latex)
cat <<EOF > "$filename".tex
\documentclass
\usepackage[utf8x]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{listings}
\usepackage[spanish]{babel}
\addtokomafont{chapterentry}{\mdseries}
\addtokomafont{chapterentry}{\rmfamily}
\setcounter{footnote}{0}
\makeatletter
\@ifundefined{date}{}{\date{}}
\makeatother
\renewcommand{\partname}{Parte}
\begin{document}
EOF

if [[ " ${included[@]} " =~ " header " ]]; then cat header.tex >> "$filename".tex 2> /dev/null; fi
if [[ " ${included[@]} " =~ " body " ]]; then cat body.tex >> "$filename".tex 2> /dev/null; fi
if [[ " ${included[@]} " =~ " footer " ]]; then cat footer.tex >> "$filename".tex 2> /dev/null; fi

# añadimos marca de fin de documento (latex)
echo '\end{document}' >> "$filename".tex


##### FORMATO A4/A5 SEGÚN PARÁMETROS #####
bookstructure() {
    # formato a5, si soporta capítulos a diferencia de scrartcl
    sed -i 's/\\subsection{\([^}]*\)}.*$/\\chapter*{\1}\n\\addcontentsline{toc}{chapter}{\1}/g' "$filename".tex
    # cambiamos section por parte
    sed -i 's/\\section{\([^}]*\)}.*$/\\part*{\1}\n\\addcontentsline{toc}{part}{\1}/g' "$filename".tex
}

articlestructure() {
    # borramos las partes, para ahorrar espacio
    # sed -i 's/\\section{\([^}]*\)}.*$//g' "$filename".tex
    sed -i 's/\\section{\([^}]*\)}.*$/\\section*{\1}\n\\addcontentsline{toc}{section}{\1}/g' "$filename".tex
    # subsecciones, no capítulos
    sed -i 's/\\subsection{\([^}]*\)}.*$/\\subsection*{\1}\n\\addcontentsline{toc}{subsection}{\1}/g' "$filename".tex
}

if [[ "$m" == 'default' ]]; then
    if [[ "$f" == *"4"* ]]; then
        mode=scrartcl
        # formato A4 scrartcl
        sed -i 's/\\documentclass.*$/\\documentclass[toc=chapterentrydotfill,'"$f"'paper]{'"$mode"'}/g' "$filename".tex
        articlestructure
    else
        # formato A5 scrbook
        sed -i 's/\\documentclass.*$/\\documentclass[toc=chapterentrydotfill,'"$f"'paper]{'"$mode"'}/g' "$filename".tex
        bookstructure
    fi
fi


##### FORMATO ARTÍCULO/LIBRO SEGÚN PARÁMETROS #####
if [[ "$m" == 'cont' ]]; then
    sed -i 's/\\documentclass.*$/\\documentclass[toc=chapterentrydotfill,'"$f"'paper]{'"$mode"'}/g' "$filename".tex
    articlestructure
else
    if [[ "$m" == 'breaks' ]]; then
        sed -i 's/\\documentclass.*$/\\documentclass[toc=chapterentrydotfill,openany,'"$f"'paper]{'"$mode"'}/g' "$filename".tex
        bookstructure
    else
        sed -i 's/\\documentclass.*$/\\documentclass[toc=chapterentrydotfill,'"$f"'paper]{'"$mode"'}/g' "$filename".tex
        bookstructure
    fi
fi


##### CONVERSIÓN A PDF #####
notvalidparts() {
    echo -e "Included parts not found or invalid syntax: $included\nPlease include your header.tex and/or footer.tex file in the same directory as your .md file"
    exit 1
}

# se compila 2 veces para obtener TOC actualizada
pdflatex -draftmode "$filename".tex >/dev/null 2>&1
pdflatex "$filename".tex >/dev/null 2>&1

if [[ "$s" != 'default' ]]; then
    scale="--noautoscale true --scale $s"
fi

if [[ ! -z "$t" ]]; then
    title="$t"
else
    title="$filename"
fi

if [[ ! -z "$a" ]]; then
    author=" --pdfauthor \"$a\" "
else
    author=''
fi

##### MAQUETADO MEDIANTE PDFJAM #####
if [[ ! -f "$filename".pdf ]]; then notvalidparts; fi
commonargs="--keepinfo --pdftitle '$title' $author $scale $filename.pdf"

if [[ "$j" != 'default' ]]; then
    if [[ "$j" == 'dual' ]]; then
        eval pdfjam --landscape --nup 2x1 --frame true $commonargs
    else
        eval pdfjam --landscape --signature\* 4 --preamble "\usepackage{everyshi}\makeatletter\EveryShipout{\ifodd\c@page\pdfpageattr{/Rotate 180}\fi}\makeatother" $commonargs
    fi
else
    eval pdfjam $commonargs
fi

mv "$filename"-pdfjam.pdf "$title".pdf >/dev/null 2>&1 &
nohup evince "$title".pdf >/dev/null 2>&1 &

##### LIMPIEZA DE FICHEROS TEMPORALES #####
rm *.toc *.dvi *.aux *.out *.log "$filename"_temp.ps "$filename".tex body.tex 2> /dev/null

