#!/bin/bash
# fist, we update the code (if the first pull fails you will need to commit the local changes you have and do `git pull`again before deploying)
cd $HOME/johgh.io-source
git pull
# this always works and is necessary to get the last (forced) commit from the source
cd source
git fetch --all
git reset --hard origin/master
git checkout master

# then, we start VM and notify changes whenever occur
cd -
vagrant up
while inotifywait -r --exclude ~/johgh.io-source/source -e close_write ~/johgh.io-source; do cd ~/johgh.io-source; vagrant ssh -c '/vagrant/shell/jkrestart.sh'; done
