#!/usr/bin/expect
set timeout 20

set pass [lindex $argv 0]
set arg1 [lindex $argv 1]
set arg2 [lindex $argv 2]

if {[llength $argv] == 3} {
    spawn git push $arg1 $arg2
} else {
    spawn git push
}

expect "*?assword*"

send $pass\r;

interact
